name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }} ${{matrix.flags}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # -- Linux --
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "8.0.2"  }
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "8.2.2"  }
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "8.4.4"  }
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "8.6.5"  }
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "8.8.4"  }
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "8.10.7" }
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "9.0.2"  }
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "9.2.8"  }
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "9.4.8"  }
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "9.4.8", flags: "-system-erf"  }
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "9.4.8", flags: "-system-expm1"}
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "9.6.4"  }
          - { cabal: "3.10", os: ubuntu-latest,  ghc: "9.8.2"  }
          # -- Win --
          - { cabal: "3.10", os: windows-latest, ghc: "8.4.4"  }
          - { cabal: "3.10", os: windows-latest, ghc: "8.6.5"  }
          - { cabal: "3.10", os: windows-latest, ghc: "8.8.4"  }
          - { cabal: "3.10", os: windows-latest, ghc: "8.10.7" }
          - { cabal: "3.10", os: windows-latest, ghc: "9.0.2"  }
          - { cabal: "3.10", os: windows-latest, ghc: "9.2.8"  }
          - { cabal: "3.10", os: windows-latest, ghc: "9.4.8"  }
          - { cabal: "3.10", os: windows-latest, ghc: "9.6.4"  }
          - { cabal: "3.10", os: windows-latest, ghc: "9.8.2"  }
          # MacOS
          - { cabal: "3.10", os: macOS-latest,   ghc: "8.4.4"  }
          - { cabal: "3.10", os: macOS-latest,   ghc: "8.6.5"  }
          - { cabal: "3.10", os: macOS-latest,   ghc: "8.8.4"  }
          - { cabal: "3.10", os: macOS-latest,   ghc: "8.10.7" }
          - { cabal: "3.10", os: macOS-latest,   ghc: "9.2.8"  }
          - { cabal: "3.10", os: macOS-latest,   ghc: "9.4.8"  }
          - { cabal: "3.10", os: macOS-latest,   ghc: "9.6.4"  }
          - { cabal: "3.10", os: macOS-latest,   ghc: "9.8.2"  }
      fail-fast: false

    steps:
    # ----------------
    - name: "Dummy"
      run: |
        echo M1 ${{ matrix.ghc }}
        echo M2 ${{ matrix.skip-bench }}
    # ----------------
    - uses: actions/checkout@v4
    # ----------------
    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    # ----------------
    - uses: actions/cache@v3
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}--${{ github.Shah }}
    # ----------------
    - name: "Install PAPI"
      run: |
        sudo apt-get install -y libpapi-dev
        echo FLAG_PAPI=-fBenchPAPI >> "$GITHUB_ENV"
      if: matrix.os == 'ubuntu-latest'
    # ----------------
    - name: Versions
      run: |
        cabal -V
        ghc -V
    # ----------------
    - name: Make sdist
      run: |
        mkdir sdist
        cabal sdist -o sdist
    - name: Unpack
      run: |
        mkdir unpacked
        tar -C unpacked -xzf sdist/math-function*tar.gz
        cd unpacked
    # ----------------
    - name: cabal check
      run: |
        cabal -vnormal check
    # ----------------
    - name: Build
      run: |
        if [ "${{ matrix.skip-test  }}" == "" ]; then FLAG_TEST=--enable-test; fi
        if [ "${{ matrix.skip-bench }}" == "" ]; then FLAG_BENCH=--enable-benchmarks; fi
        cabal configure $FLAG_PAPI $FLAG_TEST $FLAG_BENCH --flags='${{matrix.flags}}'
        cabal build all --write-ghc-environment-files=always
    # ----------------
    - name: Test
      run: |
        cabal test all
